site_name: Proyecto Intermodular ASIR
site_url: https://lidia1900.github.io/Proyecto-Intermodular-ASIR/

theme:
  name: material
  language: es
  features:
    - content.code.copy

nav:
  - Introducción: index.md
  - Utilidades:
      - Documentación: Utilidades/Documentacion.md

      
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - attr_list 
