site_name: Proyecto Intermodular ASIR
site_url: https://lidia1900.github.io/Proyecto-Intermodular-ASIR/

theme:
  name: material
  language: es
  logo: assets/images/colaborativo.png
  features:
    - content.code.copy

nav:
  - Introducción: index.md
  - Utilidades:
      - Planificación y seguimiento con Trello: Trello.md
      - Documentación: Utilidades/Documentacion.md
      - Git y entorno de desarrollo: Utilidades/Git.md

      
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
